// <auto-generated />
using System;
using ComplantSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComplantSystem.Migrations
{
    [DbContext(typeof(AppCompalintsContextDB))]
    [Migration("20220924141304_new")]
    partial class @new
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Identity")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComplantSystem.Compalints_Solution", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContentSolution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateSolution")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAccept")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolutionProvIdentity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolutionProvName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploadsComplainteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UploadsComplainteId");

                    b.HasIndex("UserId");

                    b.ToTable("Compalints_Solutions");
                });

            modelBuilder.Entity("ComplantSystem.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DirectorateId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SocietyId")
                        .HasColumnType("int");

                    b.Property<int>("SubDirectorateId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("originatorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DirectorateId");

                    b.HasIndex("GovernorateId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("SocietyId");

                    b.HasIndex("SubDirectorateId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ComplantSystem.Models.BenefCommunication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("BeneficiariesId")
                        .HasColumnType("int");

                    b.Property<string>("CommunDescribed")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("TypeCommunicationId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("BenefCommunication");
                });

            modelBuilder.Entity("ComplantSystem.Models.Communication_Counter", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BenefCommunicationId")
                        .HasColumnType("int");

                    b.Property<string>("BenefCommunicationsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BeneficiarieId")
                        .HasColumnType("int");

                    b.Property<int>("Communic_Counter")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BenefCommunicationsId");

                    b.ToTable("Communication_Counter");
                });

            modelBuilder.Entity("ComplantSystem.Models.ComplaintsRejected", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateSolution")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectedProvName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectedUserProvIdentity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploadsComplainteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("reume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UploadsComplainteId");

                    b.HasIndex("UserId");

                    b.ToTable("ComplaintsRejecteds");
                });

            modelBuilder.Entity("ComplantSystem.Models.Directorate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GovernorateId");

                    b.ToTable("Directorates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GovernorateId = 2,
                            Name = "شرعب السلام"
                        },
                        new
                        {
                            Id = 2,
                            GovernorateId = 2,
                            Name = "شرعب الرونة"
                        },
                        new
                        {
                            Id = 3,
                            GovernorateId = 1,
                            Name = "همدان"
                        },
                        new
                        {
                            Id = 4,
                            GovernorateId = 1,
                            Name = "الحيمة"
                        });
                });

            modelBuilder.Entity("ComplantSystem.Models.Governorate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Governorates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "صنعاء"
                        },
                        new
                        {
                            Id = 2,
                            Name = " تعز"
                        },
                        new
                        {
                            Id = 3,
                            Name = "الحديدة"
                        });
                });

            modelBuilder.Entity("ComplantSystem.Models.LimitationOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserResponsibleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LimitationOrders");
                });

            modelBuilder.Entity("ComplantSystem.Models.Proposal", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("BeneficiarieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateSubmeted")
                        .HasColumnType("datetime2")
                        .HasComment("تحديد وقت ادخال الصف في قاعدية البيانات");

                    b.Property<string>("DescProposal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitileProposal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proposals");
                });

            modelBuilder.Entity("ComplantSystem.Models.Society", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Societys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "جمعية البن"
                        },
                        new
                        {
                            Id = 2,
                            Name = "جمعية الالبان"
                        },
                        new
                        {
                            Id = 3,
                            Name = "جمعية الحبوب"
                        });
                });

            modelBuilder.Entity("ComplantSystem.Models.StagesComplaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StagesComplaints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "العزلة"
                        },
                        new
                        {
                            Id = 2,
                            Name = "المديرية"
                        },
                        new
                        {
                            Id = 3,
                            Name = "المحافظة"
                        },
                        new
                        {
                            Id = 4,
                            Name = "الإتحاد العام"
                        });
                });

            modelBuilder.Entity("ComplantSystem.Models.Statistics.StutusCompalintStatistic", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalCountStutus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("stutus")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("StutusCompalintStatistics");
                });

            modelBuilder.Entity("ComplantSystem.Models.Statistics.TypeCompalintStatistic", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TypeComp")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("TypeCompalintStatistics");
                });

            modelBuilder.Entity("ComplantSystem.Models.Statistics.UsersInStatistic", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Users")
                        .HasColumnType("float");

                    b.Property<string>("totalUsers")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("UsersInStatistics");
                });

            modelBuilder.Entity("ComplantSystem.Models.StatusCompalint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StatusCompalints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "جديدة"
                        },
                        new
                        {
                            Id = 2,
                            Name = "محلولة"
                        },
                        new
                        {
                            Id = 3,
                            Name = "مرفوضة"
                        },
                        new
                        {
                            Id = 4,
                            Name = "معلقة"
                        });
                });

            modelBuilder.Entity("ComplantSystem.Models.SubDirectorate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DirectorateId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DirectorateId");

                    b.ToTable("SubDirectorates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DirectorateId = 1,
                            Name = " القفاعة"
                        },
                        new
                        {
                            Id = 2,
                            DirectorateId = 1,
                            Name = " المخلاف"
                        },
                        new
                        {
                            Id = 3,
                            DirectorateId = 3,
                            Name = " بني سعد"
                        },
                        new
                        {
                            Id = 4,
                            DirectorateId = 4,
                            Name = " الاحبوب"
                        },
                        new
                        {
                            Id = 5,
                            DirectorateId = 4,
                            Name = "غوبر"
                        });
                });

            modelBuilder.Entity("ComplantSystem.Models.TypeCommunication", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsersNameAddType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeCommunications");

                    b.HasData(
                        new
                        {
                            Id = "106f08d7-704d-47ef-afe1-83959bac0345",
                            CreatedDate = new DateTime(2022, 9, 24, 17, 13, 3, 461, DateTimeKind.Local).AddTicks(9080),
                            Type = "تماطل",
                            UsersNameAddType = "قيمة افتراضية من النضام"
                        },
                        new
                        {
                            Id = "edc7c758-b763-425f-8766-3458268a5fd0",
                            CreatedDate = new DateTime(2022, 9, 24, 17, 13, 3, 461, DateTimeKind.Local).AddTicks(9627),
                            Type = "تلاعب بالحلول",
                            UsersNameAddType = "قيمة افتراضية من النضام"
                        });
                });

            modelBuilder.Entity("ComplantSystem.Models.TypeComplaint", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsersNameAddType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeComplaints");

                    b.HasData(
                        new
                        {
                            Id = "91c43602-78e3-46d5-9ea6-c8b8550bdb97",
                            CreatedDate = new DateTime(2022, 9, 24, 17, 13, 3, 462, DateTimeKind.Local).AddTicks(8862),
                            Type = "زراعية",
                            UsersNameAddType = "قيمة افتراضية من النضام"
                        },
                        new
                        {
                            Id = "9dbbf52e-378a-4039-b8e0-ab434ea7ee30",
                            CreatedDate = new DateTime(2022, 9, 24, 17, 13, 3, 462, DateTimeKind.Local).AddTicks(9491),
                            Type = "فساد",
                            UsersNameAddType = "قيمة افتراضية من النضام"
                        });
                });

            modelBuilder.Entity("ComplantSystem.Models.UpComplaintCause", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateUp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpProvName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpUserProvIdentity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploadsComplainteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UploadsComplainteId");

                    b.HasIndex("UserId");

                    b.ToTable("UpComplaintCauses");
                });

            modelBuilder.Entity("ComplantSystem.Models.UploadsComplainte", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescComplaint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DirectorateId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropBeneficiarie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Size")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("SocietyId")
                        .HasColumnType("int");

                    b.Property<int>("StagesComplaintId")
                        .HasColumnType("int");

                    b.Property<int>("StatusCompalintId")
                        .HasColumnType("int");

                    b.Property<int>("SubDirectorateId")
                        .HasColumnType("int");

                    b.Property<string>("TitleComplaint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeCommunicationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TypeComplaintId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TypeComplaintId2")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DirectorateId");

                    b.HasIndex("GovernorateId");

                    b.HasIndex("SocietyId");

                    b.HasIndex("StagesComplaintId");

                    b.HasIndex("StatusCompalintId");

                    b.HasIndex("SubDirectorateId");

                    b.HasIndex("TypeCommunicationId");

                    b.HasIndex("TypeComplaintId");

                    b.HasIndex("TypeComplaintId2");

                    b.ToTable("UploadsComplaintes");
                });

            modelBuilder.Entity("ComplantSystem.Models.UsersCommunication", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BenfId")
                        .HasColumnType("int");

                    b.Property<string>("BenfName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BenfPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DirectorateId")
                        .HasColumnType("int");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<string>("NameUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubDirectorateId")
                        .HasColumnType("int");

                    b.Property<string>("Titile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeCommuncationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DirectorateId");

                    b.HasIndex("GovernorateId");

                    b.HasIndex("SubDirectorateId");

                    b.HasIndex("TypeCommuncationId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersCommunications");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "9f120bfa-d84e-4b42-94b0-52917963ea36",
                            ConcurrencyStamp = "e4239bd8-26a7-444a-a937-d768259d893e",
                            Name = "AdminGeneralFederation",
                            NormalizedName = "ADMINGENERALFEDERATION"
                        },
                        new
                        {
                            Id = "7b5594f7-13a5-48cf-8a6c-1b2e424a32dd",
                            ConcurrencyStamp = "f0b6ce6b-d3a9-4f67-9d7a-eac807f27c1f",
                            Name = "AdminGovernorate",
                            NormalizedName = "ADMINGOVERNORATE"
                        },
                        new
                        {
                            Id = "38efefbc-95e4-4fe9-b3c4-419e5f9100c2",
                            ConcurrencyStamp = "deae4682-c543-499d-a4aa-fc21caf3df85",
                            Name = "AdminDirectorate",
                            NormalizedName = "ADMINDIRECTORATE"
                        },
                        new
                        {
                            Id = "a970a69c-8f4c-4047-95af-a61e3858945c",
                            ConcurrencyStamp = "14a6d96c-4bc7-4040-ad5c-8469fc74c454",
                            Name = "AdminSubDirectorate",
                            NormalizedName = "ADMINSUBDIRECTORATE"
                        },
                        new
                        {
                            Id = "c26e4567-332f-4150-91ea-6d7fe80315f9",
                            ConcurrencyStamp = "7800f2ee-0137-4284-b9c5-7edb359e7093",
                            Name = "Beneficiarie",
                            NormalizedName = "BENEFICIARIE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ComplantSystem.Compalints_Solution", b =>
                {
                    b.HasOne("ComplantSystem.Models.UploadsComplainte", "CompalintsHasSolution")
                        .WithMany("Compalints_Solutions")
                        .HasForeignKey("UploadsComplainteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ComplantSystem.Models.ApplicationUser", "UserAddSolution")
                        .WithMany("Compalints_Solutions")
                        .HasForeignKey("UserId");

                    b.Navigation("CompalintsHasSolution");

                    b.Navigation("UserAddSolution");
                });

            modelBuilder.Entity("ComplantSystem.Models.ApplicationUser", b =>
                {
                    b.HasOne("ComplantSystem.Models.Directorate", "Directorate")
                        .WithMany("Users")
                        .HasForeignKey("DirectorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComplantSystem.Models.Governorate", "Governorate")
                        .WithMany("Users")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComplantSystem.Models.Society", "Societies")
                        .WithMany("Users")
                        .HasForeignKey("SocietyId");

                    b.HasOne("ComplantSystem.Models.SubDirectorate", "SubDirectorate")
                        .WithMany("Users")
                        .HasForeignKey("SubDirectorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Directorate");

                    b.Navigation("Governorate");

                    b.Navigation("Societies");

                    b.Navigation("SubDirectorate");
                });

            modelBuilder.Entity("ComplantSystem.Models.Communication_Counter", b =>
                {
                    b.HasOne("ComplantSystem.Models.BenefCommunication", "BenefCommunications")
                        .WithMany("CommunicationCounters")
                        .HasForeignKey("BenefCommunicationsId");

                    b.Navigation("BenefCommunications");
                });

            modelBuilder.Entity("ComplantSystem.Models.ComplaintsRejected", b =>
                {
                    b.HasOne("ComplantSystem.Models.UploadsComplainte", "CompalintsRejected")
                        .WithMany("ComplaintsRejecteds")
                        .HasForeignKey("UploadsComplainteId");

                    b.HasOne("ComplantSystem.Models.ApplicationUser", "UserRejectComplaint")
                        .WithMany("ComplaintsRejecteds")
                        .HasForeignKey("UserId");

                    b.Navigation("CompalintsRejected");

                    b.Navigation("UserRejectComplaint");
                });

            modelBuilder.Entity("ComplantSystem.Models.Directorate", b =>
                {
                    b.HasOne("ComplantSystem.Models.Governorate", "Governorate")
                        .WithMany("Directorates")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("ComplantSystem.Models.SubDirectorate", b =>
                {
                    b.HasOne("ComplantSystem.Models.Directorate", "Directorate")
                        .WithMany("SubDirectorates")
                        .HasForeignKey("DirectorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Directorate");
                });

            modelBuilder.Entity("ComplantSystem.Models.UpComplaintCause", b =>
                {
                    b.HasOne("ComplantSystem.Models.UploadsComplainte", "CompalintUp")
                        .WithMany()
                        .HasForeignKey("UploadsComplainteId");

                    b.HasOne("ComplantSystem.Models.ApplicationUser", "UserUpComplaint")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("CompalintUp");

                    b.Navigation("UserUpComplaint");
                });

            modelBuilder.Entity("ComplantSystem.Models.UploadsComplainte", b =>
                {
                    b.HasOne("ComplantSystem.Models.Directorate", "Directorate")
                        .WithMany("UploadsComplaintes")
                        .HasForeignKey("DirectorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComplantSystem.Models.Governorate", "Governorate")
                        .WithMany("UploadsComplaintes")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComplantSystem.Models.Society", "Society")
                        .WithMany()
                        .HasForeignKey("SocietyId");

                    b.HasOne("ComplantSystem.Models.StagesComplaint", "StagesComplaint")
                        .WithMany("UploadsComplainte")
                        .HasForeignKey("StagesComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComplantSystem.Models.StatusCompalint", "StatusCompalint")
                        .WithMany("UploadsComplainte")
                        .HasForeignKey("StatusCompalintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComplantSystem.Models.SubDirectorate", "SubDirectorate")
                        .WithMany("UploadsComplaintes")
                        .HasForeignKey("SubDirectorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComplantSystem.Models.TypeCommunication", null)
                        .WithMany("UploadsComplainte")
                        .HasForeignKey("TypeCommunicationId");

                    b.HasOne("ComplantSystem.Models.TypeComplaint", "TypeComplaint")
                        .WithMany()
                        .HasForeignKey("TypeComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComplantSystem.Models.TypeComplaint", null)
                        .WithMany("UploadsComplaintes")
                        .HasForeignKey("TypeComplaintId2")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Directorate");

                    b.Navigation("Governorate");

                    b.Navigation("Society");

                    b.Navigation("StagesComplaint");

                    b.Navigation("StatusCompalint");

                    b.Navigation("SubDirectorate");

                    b.Navigation("TypeComplaint");
                });

            modelBuilder.Entity("ComplantSystem.Models.UsersCommunication", b =>
                {
                    b.HasOne("ComplantSystem.Models.Directorate", "Directorate")
                        .WithMany("UsersCommunications")
                        .HasForeignKey("DirectorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComplantSystem.Models.Governorate", "Governorate")
                        .WithMany("UsersCommunications")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComplantSystem.Models.SubDirectorate", "SubDirectorate")
                        .WithMany("UsersCommunications")
                        .HasForeignKey("SubDirectorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComplantSystem.Models.TypeCommunication", "TypeCommunication")
                        .WithMany("UsersCommunications")
                        .HasForeignKey("TypeCommuncationId");

                    b.HasOne("ComplantSystem.Models.ApplicationUser", "User")
                        .WithMany("UsersCommunications")
                        .HasForeignKey("UserId");

                    b.Navigation("Directorate");

                    b.Navigation("Governorate");

                    b.Navigation("SubDirectorate");

                    b.Navigation("TypeCommunication");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.HasOne("ComplantSystem.Models.ApplicationUser", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ComplantSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ComplantSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComplantSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ComplantSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComplantSystem.Models.ApplicationUser", b =>
                {
                    b.Navigation("Compalints_Solutions");

                    b.Navigation("ComplaintsRejecteds");

                    b.Navigation("UserRoles");

                    b.Navigation("UsersCommunications");
                });

            modelBuilder.Entity("ComplantSystem.Models.BenefCommunication", b =>
                {
                    b.Navigation("CommunicationCounters");
                });

            modelBuilder.Entity("ComplantSystem.Models.Directorate", b =>
                {
                    b.Navigation("SubDirectorates");

                    b.Navigation("UploadsComplaintes");

                    b.Navigation("Users");

                    b.Navigation("UsersCommunications");
                });

            modelBuilder.Entity("ComplantSystem.Models.Governorate", b =>
                {
                    b.Navigation("Directorates");

                    b.Navigation("UploadsComplaintes");

                    b.Navigation("Users");

                    b.Navigation("UsersCommunications");
                });

            modelBuilder.Entity("ComplantSystem.Models.Society", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ComplantSystem.Models.StagesComplaint", b =>
                {
                    b.Navigation("UploadsComplainte");
                });

            modelBuilder.Entity("ComplantSystem.Models.StatusCompalint", b =>
                {
                    b.Navigation("UploadsComplainte");
                });

            modelBuilder.Entity("ComplantSystem.Models.SubDirectorate", b =>
                {
                    b.Navigation("UploadsComplaintes");

                    b.Navigation("Users");

                    b.Navigation("UsersCommunications");
                });

            modelBuilder.Entity("ComplantSystem.Models.TypeCommunication", b =>
                {
                    b.Navigation("UploadsComplainte");

                    b.Navigation("UsersCommunications");
                });

            modelBuilder.Entity("ComplantSystem.Models.TypeComplaint", b =>
                {
                    b.Navigation("UploadsComplaintes");
                });

            modelBuilder.Entity("ComplantSystem.Models.UploadsComplainte", b =>
                {
                    b.Navigation("Compalints_Solutions");

                    b.Navigation("ComplaintsRejecteds");
                });
#pragma warning restore 612, 618
        }
    }
}
